# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VADAHUB
email: thyun@synctechno.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vadahub.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll


repository: vadahub/vadahub.github.io # username.github.io repository를 적어주면 된다.
permalink: /:year/:month/:day/:title/ # url을 어떻게 구성할 건지 묻는 것
excerpt_separator: <!--more--> # post에서 추출할 때 무엇을 기준으로 추출할 것인지 주로 미리보기에 사용된다.


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

gems:
  - jekyll-paginate # 페이지 네이션 설정

paginate: 5 # 몇 개의 포스트를 1개 페이지에 표시할 것인지
paginate_path: '/page/:num/' # 페이지네이션 경로

exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock] # Jekyll이 무시할 목록

keep_files: [assets, files] # 유지할 파일들

author: vadahub # author
asset_url: /assets # assets의 경로
image: 'vadahub-logo.png' # 블로그 기본 이미지